name: Auto Label Based on Branch Name

on:
  pull_request:
    types: [opened, synchronize] # PRが作成されたり更新されたときに実行

jobs:
  add-label:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Add label based on branch name
      env:
        BRANCH_NAME: ${{github.head_ref}}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(`Branch name: ${process.env.BRANCH_NAME}`);
            # const branchName = github.context.payload.pull_request.head.ref;
            const branchName = github.head_ref;
            console.log(`Branch name: ${branchName}`);
            const labels = [];
            
            if (branchName.startsWith("feature/")) {
              labels.push("enhancement");
            } else if (branchName.startsWith("bugfix/")) {
              labels.push("bugfix");
            }

            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: github.context.payload.pull_request.number,
                labels: labels,
              });
            }