name: Build and Release on Tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]'

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create Release
        run: |
          gh release create ${{github.ref_name}} --generate-notes
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}